channels:
  - conda-forge
dependencies:
  - python=3.8
  - iris==3.0.1
  - pip
  - pip:
    - matplotlib
    - numpy
    - hvplot
    - tensorflow==2.2.0
    - geoviews
    - urllib3
    - imageio
    - ipywidgets
    - pandas
    - tqdm
    - xarray